config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: :callbacks
  }
  root "games#index"
  resources :involved_companies
  resources :genres
  resources :platforms
  resources :games do
    resources :critics, only: :create
  end
  resources :critics
  resources :companies  do
    resources :critics, only: :create
  end
  # resources :users
  #get 'signup', to: 'users#new'
  #post 'signup', to: 'users#create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get '/auth/:twitter2/callback', to: 'sessions#create'
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  before_action :set_platform, only: %i[ show edit update destroy ]

  # GET /platforms
  def index
    @platforms = Platform.all
  end

  # GET /platforms/1
  def show
  end

  # GET /platforms/new
  def new
    @platform = Platform.new
  end

  # GET /platforms/1/edit
  def edit
  end

  # POST /platforms
  def create
    game = Game.find(params[:game_id])
    platform = Platform.find_by(name: params[:name])
    game.platforms.push(platform)
    redirect_to game_path(:game_id)
  end

  # PATCH/PUT /platforms/1
  def update
    if @platform.update(platform_params)
      redirect_to @platform, notice: "Platform was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /platforms/1
  def destroy
    @platform.destroy
    redirect_to game_path(:game_id), notice: "Platform was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_platform
      @platform = Platform.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def platform_params
      params.require(:platform).permit(:name, :category)
    end
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/views/platforms/_form.html.erb
<%= form_with(model: platform) do |form| %>
  <% if platform.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(platform.errors.count, "error") %> prohibited this platform from being saved:</h2>

      <ul>
        <% platform.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.number_field :category %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/platforms/_platform.html.erb
<div id="<%= dom_id platform %>">
  <p>
    <strong>Name:</strong>
    <%= platform.name %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= platform.category %>
  </p>

</div>

app/views/platforms/edit.html.erb
<h1>Editing platform</h1>

<%= render "form", platform: @platform %>

<br>

<div>
  <%= link_to "Show this platform", @platform %> |
  <%= link_to "Back to platforms", platforms_path %>
</div>

app/views/platforms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Platforms</h1>

<div id="platforms">
  <% @platforms.each do |platform| %>
    <%= render platform %>
    <p>
      <%= link_to "Show this platform", platform %>
    </p>
  <% end %>
</div>

<%= link_to "New platform", new_platform_path %>

app/views/platforms/new.html.erb
<h1>New platform</h1>

<%= render "form", platform: @platform %>

<br>

<div>
  <%= link_to "Back to platforms", platforms_path %>
</div>

app/views/platforms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @platform %>

<div>
  <%= link_to "Edit this platform", edit_platform_path(@platform) %> |
  <%= link_to "Back to platforms", platforms_path %>

  <%= button_to "Destroy this platform", @platform, method: :delete %>
</div>