config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: :callbacks
  }
  root "games#index"
  resources :involved_companies
  resources :genres
  resources :platforms
  resources :games do
    resources :critics, only: :create
  end
  resources :critics
  resources :companies  do
    resources :critics, only: :create
  end
  # resources :users
  #get 'signup', to: 'users#new'
  #post 'signup', to: 'users#create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get '/auth/:twitter2/callback', to: 'sessions#create'
end

app/models/game.rb
class Game < ApplicationRecord
  has_one_attached :image
  belongs_to :parent, class_name: "Game", optional: true
  has_many :involved_companies, dependent: :destroy
  has_many :companies, through: :involved_companies
  has_and_belongs_to_many :platforms
  has_and_belongs_to_many :genres
  has_many :critics, as: :criticable, dependent: :destroy

  enum category: { main_game: 0, expansion: 1 }

  validates :name, presence: true, uniqueness: true
  validates :category, presence: true
  validates :rating,
            numericality: {
              greater_than_or_equal_to: 0,
              less_than_or_equal_to: 100,
              allow_nil: true
            }

  validate :validate_parent

  private

  def validate_parent
    if category == "main_game" && parent_id
      errors.add(:parent_id, "Should be null")
    elsif category == "expansion" && Game.find_by(id: parent_id).nil?
      errors.add(:parent_id, "Should be a valid game id")
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games
  def index
    @games = Game.all
  end

  # GET /games/1
  def show
    @game = Game.find(params[:id])
 
  end

  # GET /games/new
  def new
    @game = Game.new
    authorize @game
  end

  # GET /games/1/edit
  def edit
    authorize @game
  end

  # POST /games
  def create
    @game = Game.new(game_params)

    if @game.save
      redirect_to @game, notice: "Game was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /games/1
  def update
    if @game.update(game_params)
      redirect_to @game, notice: "Game was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /games/1
  def destroy
    @game.destroy
    authorize @game
    redirect_to games_url, notice: "Game was successfully destroyed."
  end

  private

    # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def game_params
    params.require(:game).permit(:name, :summary, :release_date, :category, :rating, :parent_id, :image)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, class:"block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :name ,class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"%>
  </div>

  <div>
    <%= form.label :summary, class:"block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_area :summary, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div>
    <%= form.label :release_date, class:"block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.date_field :release_date, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div>
    <%= form.label :rating, class:"block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :rating, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div>
    <%= form.label :category, class:"block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :category, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>


  <div>
    <%= form.label :parent_id, class:"block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :parent_id, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div>
  <%if game.image.attached?%>
  <%= image_tag game.image %>
   <%end%>
  </div>

  <div>
  <%= form.label :cover %>
  <br>
  <%= form.file_field :image, accept: 'image/png,image/jpeg'%>
  <% game.errors.full_messages_for(:image).each do |message|%>
  <span>
  <%= message%>
  </span>
  <%end%>
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
  <p>
    <strong>Name:</strong>
    <%= game.name %>
  </p>

  <p>
    <strong>Summary:</strong>
    <%= game.summary %>
  </p>

  <p>
    <strong>Release date:</strong>
    <%= game.release_date %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= game.category %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= game.rating %>
  </p>

  <p>
    <strong>Parent:</strong>
    <%= game.parent_id %>
  </p>

</div>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%# link_to "Show this game", @game %>
  <%= link_to "Back", games_path %>
</div>

app/views/games/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container mx-auto pt-5">
<h1 class="mb-2 text-5xl text-center font-bold tracking-tight text-gray-800">Games</h1>
<% if current_user.admin? %>
 <%= link_to 'New game', new_game_path, class:"mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-black" %>
 <% end %>
 <hr>
 <br>

<div id="games" >
  <% @games.each do |game| %>
  <%= link_to game do%>
          <div class="flex flex-col items-center border rounded-lg shadow-xl md:flex-row md:max-w-3xl border-gray-700 bg-gray-800 hover:bg-gray-700">
            <div>
               <%if game.image.attached?%>
               <div class="h-50 w-full rounded-t-lg object-cover md:h-auto md:w-48 md:rounded-none md:rounded-l-lg">
                  <%= image_tag game.image%>
               </div>
               <%end%>
            </div>
            <div class="flex flex-col justify-start p-6">
            <h3 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= game.name %></h3>
            <div>
               <%if game.release_date%>
               <div class="text-xl text-white">
                  <%= game.release_date.year %>
               </div>
               <%end%>
            </div>
            <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"><%= game.rating %></p>
            <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"><%= game.summary %></p>
            
            <% if current_user.admin? %>
            <%= link_to 'Edit', edit_game_path(game), class:"mb-4 block items-center px-4 py-2 text-sm font-medium text-center text-gray-900 bg-white border border-gray-300 rounded-lg hover:bg-blue-500 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-400 dark:hover:border-gray-700 dark:focus:ring-gray-700" %>
            <%= link_to 'Destroy', game, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:"block items-center px-4 py-2 text-sm font-medium text-center text-gray-900 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-400 dark:hover:border-gray-700 dark:focus:ring-gray-700" %>
            <% end %>
          </div>
          </div>
           <br>
        <% end %>
   <%end%>

        


</div>
</div>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Back", games_path %>
</div>

app/views/games/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <%if @game.image.attached?%>
  <div>
     <%= image_tag @game.image%>
  </div>
  <%end%>
</div>
<h3><%= @game.name %></h3>
<div>
   <%if @game.release_date%>
   <div>
      <%= @game.release_date.year %>
   </div>
   <%end%>
</div>
<p><%= @game.rating %></p>
<p><%= @game.summary %></p>
<div>
   <%if @game.genres%>
   <div>
      <p>Genres:<% @game.genres.each do |genre| %>
      <div>
       <%= button_to  genre_path(genre), method: :delete do %> 
       <%= image_tag "delete_icon.png", alt: "Delete Genre" %>
       <%= genre.name %>
       <% end %>
      </div>
      </p>
      <%end%>
   </div>
   <%end%>
</div>
<div>
   <%if @game.platforms%>
   <div>
      <p>Platforms:<% @game.platforms.each do |platform| %>
      <div>
       <%= button_to  platform_path(platform), method: :delete do %> 
       <%= image_tag "delete_icon.png", alt: "Delete Platform" %>
       <%= platform.name %>
       <% end %>
      </div>
      </p>
      <%end%>
   </div>
   <%end%>
</div>
<div>
   <%if @game.companies%>
   <div>
      <p>Developers:<% @game.involved_companies.where(developer: true).each do |company| %>
      <div>
      <%= button_to  company_path(company), method: :delete do %> 
       <%= image_tag "delete_icon.png", alt: "Delete Developer" %>
       <%= Company.all.find(company.company_id).name %>
       <% end %>
      </div>
      </p>
      <%end%>
   </div>
   <%end%>

   <%if @game.companies%>
   <div>
      <p>Publishers:<% @game.involved_companies.where(publisher: true).each do |company| %>
      <div>
      <%= button_to  company_path(company), method: :delete do %> 
       <%= image_tag "delete_icon.png", alt: "Delete Developer" %>
       <%= Company.all.find(company.company_id).name %>
       <% end %>
      </div>
      </p>
      <%end%>
   </div>
   <%end%>
</div>

<h2>Add relations</h2>
<% names = [] %>
<%= form_with(url: genres_path, method: "post") do |form| %>
  <div>
  <% options = Genre.all.each{ |option| names << option[:name] } %>
  <% options_for_select = names.each{ |option| option } %>
    <%= form.select :name, options_for_select([["Select genre", nil]] + options_for_select) %>
    <%= form.hidden_field :game_id, value: @game.id %>
    <%= form.submit "Add genre" %>
  </div>
<% end %>

<%= form_with(url: platforms_path, method: "post") do |form| %>
  <div>
  <% options = Platform.all %>
  <% options_for_select = options.map { |option| option.name } %>
    <%= form.select :name, options_for_select([["Select platform", nil]] + options_for_select) %>
    <%= form.hidden_field :game_id, value: @game.id %>
    <%= form.submit "Add platform" %>
  </div>
<% end %>

<%= form_with(url: companies_path, method: "post") do |form| %>
  <div>
  <% options = Company.all %>
  <% options_for_select = options.map { |option| option.name } %>
  <%= form.hidden_field :company, value: "developer" %>
    <%= form.select :name, options_for_select([["Select company", nil]] + options_for_select) %>
    <%= form.hidden_field :game_id, value: @game.id %>
    <%= form.submit "Add developer" %>
  </div>
<% end %>

<%= form_with(url: companies_path, method: "post") do |form| %>
  <div>
  <% options = Company.all %>
  <% options_for_select = options.map { |option| option.name } %>
  <%= form.hidden_field :company, value: "publisher" %>
    <%= form.select :name, options_for_select([["Select company", nil]] + options_for_select) %>
    <%= form.hidden_field :game_id, value: @game.id %>
    <%= form.submit "Add publisher" %>
  </div>
<% end %>

<br>
<%= form_with(url: game_critics_path(params[:id]), method:"post") do |form| %>
  <div>
    <%= form.text_field :title, placeholder: "Critic title" %>
  </div>

  <div>
    <%= form.text_field :body, placeholder: "Critic body" %>
  </div>

   <div>
    <%= form.submit "Create critic" %>
  </div>
<%end%>

<br>
<div>
   <%if @game.critics%>
   <%@game.critics.each do |critic|%>
   <%= critic.title %></p>
   by <%= critic.user.username %></p>
   <%= critic.body %></p>
   <%# <% reference_time = Time.zone.now - 10.day %>
   <% timestamp = critic.created_at%>
   Send <%= time_ago_in_words(timestamp) %> ago</p>
   <%end%>
   <%end%>
</div>

<div>
  <%= link_to "Back", games_path %>
</div>