config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: :callbacks
  }
  root "games#index"
  resources :involved_companies
  resources :genres
  resources :platforms
  resources :games do
    resources :critics, only: :create
  end
  resources :critics
  resources :companies  do
    resources :critics, only: :create
  end
  # resources :users
  #get 'signup', to: 'users#new'
  #post 'signup', to: 'users#create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get '/auth/:twitter2/callback', to: 'sessions#create'
end

app/models/company.rb
class Company < ApplicationRecord
  has_one_attached :cover
  has_many :involved_companies, dependent: :destroy
  has_many :games, through: :involved_companies

  has_many :critics, as: :criticable, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]

  # GET /companies
  def index
    @companies = Company.all
  end

  # GET /companies/1
  def show
    
  end

  # GET /companies/new
  def new
    @company = Company.new
    authorize @company
  end

  # GET /companies/1/edit
  def edit
    authorize @company
  end

  # POST /companies
  def create
    game = Game.find(params[:game_id])
    if params[:company] == "developer"
      company = Company.find_by(name: params[:name])
      game.involved_companies.create(company_id: company.id, developer: true, publisher: false)
    elsif params[:company] == "publisher"
      company = Company.find_by(name: params[:name])
      game.involved_companies.create(company_id: company.id, developer: false, publisher: true)
    end
    redirect_to game_path(:game_id)
  end

  # PATCH/PUT /companies/1
  def update
    if @company.update(company_params)
      redirect_to @company, notice: "Company was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /companies/1
  def destroy
    @company.destroy
    authorize @company
    redirect_to game_path(:game_id), notice: "Company was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :description, :start_date, :country, :cover)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.erb
<div id="<%= dom_id company %>">
  <p>
    <strong>Name:</strong>
    <%= company.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= company.description %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= company.start_date %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= company.country %>
  </p>

</div>

app/views/companies/_form.html.erb
<div class="mx-auto">
<%= form_with(model: company) do |form| %>
  <% if company.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, class:"block text-gray-700 text-xl font-bold mb-2" %>
    <%= form.text_field :name,class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div>
    <%= form.label :description,  class:"block text-gray-700 text-xl font-bold mb-2" %>
    <%= form.text_area :description, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div>
    <%= form.label :start_date, class:"block text-gray-700 text-xl font-bold mb-2" %>
    <%= form.date_field :start_date, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div>
    <%= form.label :country, class:"block text-gray-700 text-xl font-bold mb-2" %>
    <%= form.text_field :country, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div >
  <%if company.cover.attached?%>
  <%= image_tag company.cover ,class:"object-contain h-60 w-100"%>
   <%end%>
  </div>

  <div>
  <%= form.label :cover %>
  <br>
  <%= form.file_field :cover, accept: 'image/png,image/jpeg',class:"w-100" %>
  <% company.errors.full_messages_for(:cover).each do |message|%>
  <span>
  <%= message%>
  </span>
  <%end%>
</div>

  <div>
    <%= form.submit class:"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>
</div>

app/views/companies/edit.html.erb
<h1 class="font-montserrat font-semibold" >Editing company</h1>

<%= render "form", company: @company %>

<br>

<div class="font-montserrat font-semibold shadow appearance-none w-full py-2 px-300" >
  <%= link_to "Back", companies_path %>
</div>

app/views/companies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Companies</h1>
<% if current_user.admin? %>
 <%= link_to 'New Company', new_company_path %>
 <% end %>
<div id="games">
  <% @companies.each do |company| %>
  <%= link_to company do%>
          <div>
            <div>
               <%if company.cover.attached?%>
               <div>
                  <%= image_tag company.cover%>
               </div>
               <%end%>
            </div>
            <h3><%= company.name %></h3>
            <div>
               <%if company.start_date %>
               <div>
                  <%= company.start_date.year %>
               </div>
               <%end%>
               <%= company.country %>

            </div>
            <p><%= company.description %></p>
            <p><%= company.games.size %></p>
            
            <% if current_user.admin? %>
            <%= link_to 'Edit', edit_company_path(company) %>
            <%= link_to 'Destroy', company, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        <% end %>
   <%end%>
</div>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render "form", company: @company %>

<br>

<div>
  <%= link_to "Back", companies_path %>
</div>

app/views/companies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @company %>

<div>
  <%= link_to "Edit this company", edit_company_path(@company) %> |
  <%= link_to "Back to companies", companies_path %>

  <%= button_to "Destroy this company", @company, method: :delete %>
</div>

<%= form_with(url: company_critics_path(params[:id]), method:"post") do |form| %>
  <div>
    <%= form.text_field :title, placeholder: "Critic title" %>
  </div>

  <div>
    <%= form.text_field :body, placeholder: "Critic body" %>
  </div>

   <div>
    <%= form.submit "Create critic" %>
  </div>
<%end%>
 <%# button_to "Destroy this critic", @company.critics(params[:id]), method: :delete %>

<div>
   <%if @company.critics%>
   <%@company.critics.each do |critic|%>
   <%= critic.title %></p>
   by <%= critic.user.username %></p>
   <%= critic.body %></p>
   <%# <% reference_time = Time.zone.now - 10.day %>
   <% timestamp = critic.created_at%>
   Send <%= time_ago_in_words(timestamp) %> ago</p>
   <%end%>
   <%end%>
</div>